# Generated by Django 2.2.3 on 2019-08-03 02:35

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=257)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('hot', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('img', models.FileField(upload_to='banner')),
                ('banner_url', models.CharField(max_length=500)),
                ('ordering', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ditie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fangdong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('sum_chuzu', models.IntegerField()),
                ('recently_sum_chuzu', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('room_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=15)),
                ('xianjia', models.IntegerField()),
                ('hot', models.IntegerField()),
                ('update_data', models.DateTimeField(auto_now=True)),
                ('orientation', models.IntegerField(choices=[(1, '朝南'), (2, '朝北'), (3, '朝东'), (4, '朝西')])),
                ('protocol', models.TextField()),
                ('allocation', models.ManyToManyField(to='home.Allocation')),
                ('expenses', models.ManyToManyField(to='home.Expenses')),
                ('fangdong', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fangzi', to='home.Fangdong')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kuaixun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('kuaixun_img', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nav_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('xuanchuan_img', models.FileField(upload_to='Room_type')),
                ('url', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zhoubian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('hot', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='other_Room_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('or_id', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, '已租'), (2, '空闲')])),
                ('expiration_Date', models.DateTimeField()),
                ('have_windows', models.BooleanField()),
                ('have_yangtai', models.BooleanField()),
                ('have_selfwc', models.BooleanField()),
                ('hous', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_Room_details', to='home.Housing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('nav_url', models.CharField(max_length=32)),
                ('nav_ordering', models.IntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nav', to='home.Nav_title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Housing_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('img_url', models.CharField(max_length=256)),
                ('the_hourse_img', models.FileField(upload_to='housing')),
                ('is_first', models.BooleanField(default=False)),
                ('the_hourse', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='housing_img', to='home.Housing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Housing_estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=32)),
                ('hot', models.IntegerField(default=0)),
                ('ditie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Ditie')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Transportation')),
                ('xiaozheng', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Town')),
                ('zhoubian', models.ManyToManyField(to='home.Zhoubian')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='housing',
            name='xiaoqu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Housing_estate'),
        ),
        migrations.AddField(
            model_name='housing',
            name='zhoubian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Zhoubian'),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
