# Generated by Django 2.2.3 on 2019-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_housing_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='size',
            field=models.CharField(default='22pinfang', max_length=64),
            preserve_default=False,
        ),
    ]
