# Generated by Django 2.2.3 on 2019-08-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_housing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
