# Generated by Django 2.2.3 on 2019-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='hot',
            field=models.IntegerField(default=0),
        ),
    ]
