# Generated by Django 2.2.3 on 2019-07-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.FileField(upload_to='banner'),
        ),
    ]
