# Generated by Django 2.2.3 on 2019-07-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190727_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='url',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
