# Generated by Django 2.2.3 on 2019-07-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190727_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing_img',
            name='the_hourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='housing_img', to='home.Housing'),
        ),
    ]
