# Generated by Django 2.2.3 on 2019-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190729_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing_img',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housing_img',
            name='the_hourse_img',
            field=models.FileField(null=True, upload_to='housing'),
        ),
    ]
