# Generated by Django 2.2.3 on 2019-07-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190729_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Area'),
        ),
    ]
