# Generated by Django 2.2.3 on 2019-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_town_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='update_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='housing_img',
            name='is_first',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
