# Generated by Django 2.2.3 on 2019-07-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190730_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ditie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
