# Generated by Django 2.2.3 on 2019-07-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_ditie'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing_estate',
            name='ditie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Ditie'),
        ),
    ]
