# Generated by Django 2.2.3 on 2019-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_housing_estate_ditie'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='addr',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
