# Generated by Django 2.2.3 on 2019-07-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_housing_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fangdong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('sum_chuzu', models.IntegerField()),
                ('recently_sum_chuzu', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='other_Room_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('or_id', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, '已租'), (2, '空闲')])),
                ('expiration_Date', models.DateTimeField()),
                ('have_windows', models.BooleanField()),
                ('have_yangtai', models.BooleanField()),
                ('have_selfwc', models.BooleanField()),
                ('protocol', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_dele', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='room',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='addr',
        ),
        migrations.AddField(
            model_name='ditie',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='expenses',
            field=models.ManyToManyField(to='home.Expenses'),
        ),
        migrations.AddField(
            model_name='housing',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='now_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='orientation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='yuanjia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housing_estate',
            name='addr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RemoveField(
            model_name='housing_estate',
            name='zhoubian',
        ),
        migrations.AddField(
            model_name='housing_estate',
            name='zhoubian',
            field=models.ManyToManyField(null=True, to='home.Zhoubian'),
        ),
        migrations.AddField(
            model_name='housing',
            name='allocation',
            field=models.ManyToManyField(to='home.Allocation'),
        ),
        migrations.AddField(
            model_name='housing',
            name='fangdong',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fangzi', to='home.Fangdong'),
        ),
        migrations.AddField(
            model_name='housing',
            name='other_Room_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.other_Room_details'),
        ),
        migrations.AddField(
            model_name='housing_estate',
            name='transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Transportation'),
        ),
    ]
