# Generated by Django 2.2.3 on 2019-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190731_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='now_price',
        ),
        migrations.AddField(
            model_name='housing',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
