# Generated by Django 2.2.3 on 2019-07-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190731_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='orientation',
            field=models.IntegerField(choices=[(1, '朝南'), (2, '朝北'), (3, '朝东'), (4, '朝西')]),
        ),
    ]
