# Generated by Django 2.2.3 on 2019-08-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190731_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='other_Room_details',
        ),
        migrations.AddField(
            model_name='other_room_details',
            name='fangzi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_Room_details', to='home.Housing'),
        ),
    ]
