# Generated by Django 2.2.3 on 2019-08-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190801_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_room_details',
            name='fangzi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_Room_details', to='home.Housing'),
        ),
    ]
