# Generated by Django 2.2.3 on 2019-08-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190801_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_room_details',
            name='fangzi',
        ),
        migrations.AddField(
            model_name='housing',
            name='other_Room_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.other_Room_details'),
        ),
    ]
