# Generated by Django 2.2.3 on 2019-08-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190801_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='other_Room_details',
        ),
    ]
