# Generated by Django 2.2.3 on 2019-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_housing_other_room_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing_estate',
            name='zhoubian',
            field=models.ManyToManyField(to='home.Zhoubian'),
        ),
    ]
