# Generated by Django 2.2.3 on 2019-08-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190801_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_room_details',
            name='hous',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Housing'),
            preserve_default=False,
        ),
    ]
