# Generated by Django 2.2.3 on 2019-08-01 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_other_room_details_hous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_room_details',
            name='hous',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_Room_details', to='home.Housing'),
        ),
    ]
