# Generated by Django 2.2.3 on 2019-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190801_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='protocol',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
