# Generated by Django 2.2.3 on 2019-08-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_housing_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_room_details',
            name='protocol',
        ),
    ]
